apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-ui
  template:
    metadata:
      labels:
        app: broken-ui
    spec:
      containers:
      - name: broken-ui
        image: nginx:DOESNOTEXIST
        ports:
        - containerPort: 80